CREATE TABLE `LIBROS` (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
  `ISBN` varchar(255) NOT NULL,
  `TITULO` varchar(255) NOT NULL,
  `AUTOR` varchar(255) NOT NULL,
  `year` int(11) NOT NULL,
  `PORTADA_URL` varchar(255),
  `EDITORIAL` varchar(255) NOT NULL,
  `CATEGORIA_ID` int(11) NOT NULL
  `SINOPSIS` text DEFAULT NULL
);

CREATE TABLE USERS(
    ID int(11) PRIMARY KEY NOT NULL,
    NAME varchar(255) NOT NULL,
    CP INT NOT NULL,
    CORREO VARCHAR(255) NOT NULL,
    FECHA_NACIMIENTO DATE,
    PASS TEXT NOT NULL
);

CREATE TABLE REVIEWS(
    ID_PUBLICACION INT (11),
    ID_USER INT(11),
    CONTENIDO TEXT,
    CALIFICACION INT(2)
);

CREATE TABLE BIBLIOTECAS(
    ID INT(11) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    CP INT(11) NOT NULL
);

CREATE TABLE INVENTARIO ( 
    ISBN INT (11) PRIMARY KEY NOT NULL,
    ID_BIBLIOTECA INT(11) NOT NULL,
    EXISTENCIAS INT NOT NULL
)
CREATE TABLE CATEGORIAS ( 
    ID INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL
)